EMPTY_UCSO = {
    "ucso_version": 1,
    "applicant": {},
    "compliance": {"status": "PENDING", "missing_documents": [], "checked_at": ""},
    "documents": {"files": []},
    "financials": {},
    "derived_features": {},
    "gst_analysis": {"reconciliation_status": "PENDING"},
    "bank_reconciliation": {"reconciliation_verdict": "PENDING"},
    "mca_intelligence": {"company_status": "UNKNOWN"},
    "pan_intelligence": {"status": "PENDING"},
    "web_intel": {},
    "pd_intelligence": {},
    "risk": {"band": "PENDING", "decision": "PENDING"},
    "bias_checks": {"counterfactual_tested": False},
    "stress_results": {"scenarios": [], "survival_verdict": "PENDING"},
    "ews_monitoring": {"enabled": False},
    "decision_confidence": {},
    "cam_output": {},
    "human_notes": {"notes": []},
    "audit_log": [],
}
